#!/usr/bin/env node
/**
 * Red Rugger LLC — static site builder
 * ------------------------------------
 * Assembles pages from src/partials + src/pages into dist/.
 * No dependencies. Run:  node build.js
 *
 * Each file in src/pages/ begins with a JSON front-matter block fenced by
 * <!--meta ... meta-->. Everything after it is the page body.
 *
 *   <!--meta
 *   { "slug": "index", "title": "...", "description": "...", "nav": "home" }
 *   meta-->
 */

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'src');
const PAGES = path.join(SRC, 'pages');
const PARTIALS = path.join(SRC, 'partials');
const DIST = path.join(__dirname, 'dist');

const SITE = {
  name: 'Red Rugger LLC',
  url: 'https://www.redruggerllc.com',
  phone: '917-682-3642',
  phoneHref: 'tel:+19176823642',
  email: 'redrugger1949@gmail.com',
  year: new Date().getFullYear(),
};

const read = (p) => fs.readFileSync(p, 'utf8');

function parsePage(raw) {
  const m = raw.match(/<!--meta([\s\S]*?)meta-->/);
  if (!m) throw new Error('Page is missing its <!--meta ... meta--> block.');
  const meta = JSON.parse(m[1].trim());
  const body = raw.slice(m.index + m[0].length).trim();
  return { meta, body };
}

/** Replace {{token}} with values from the context. Unknown tokens are left alone. */
function fill(tpl, ctx) {
  return tpl.replace(/\{\{\s*([\w.]+)\s*\}\}/g, (whole, key) => {
    const val = key.split('.').reduce((o, k) => (o == null ? o : o[k]), ctx);
    return val == null ? whole : String(val);
  });
}

/** Mark the active top-level nav item so the header can highlight it. */
function markActiveNav(headerHtml, navKey) {
  if (!navKey) return headerHtml;
  return headerHtml.replace(
    new RegExp(`(<(?:a|button)[^>]*data-nav="${navKey}"[^>]*)(>)`, 'g'),
    '$1 aria-current="page"$2'
  );
}

function build() {
  const shell = read(path.join(PARTIALS, 'shell.html'));
  const header = read(path.join(PARTIALS, 'header.html'));
  const footer = read(path.join(PARTIALS, 'footer.html'));

  if (!fs.existsSync(DIST)) fs.mkdirSync(DIST, { recursive: true });

  const files = fs.readdirSync(PAGES).filter((f) => f.endsWith('.html'));
  const built = [];

  for (const file of files) {
    const { meta, body } = parsePage(read(path.join(PAGES, file)));
    const ctx = { ...SITE, ...meta, site: SITE };

    const html = fill(shell, {
      ...ctx,
      header: markActiveNav(fill(header, ctx), meta.nav),
      footer: fill(footer, ctx),
      body: fill(body, ctx),
      bodyClass: meta.bodyClass || '',
      schema: meta.schema ? `\n<script type="application/ld+json">${JSON.stringify(meta.schema)}</script>` : '',
    });

    const out = path.join(DIST, `${meta.slug}.html`);
    fs.writeFileSync(out, html, 'utf8');
    built.push(`${meta.slug}.html`);
  }

  // sitemap.xml — every built page, so search engines find the new fund pages.
  const urls = built
    .map((f) => {
      const loc = f === 'index.html' ? `${SITE.url}/` : `${SITE.url}/${f.replace('.html', '/')}`;
      const priority = f === 'index.html' ? '1.0' : f.startsWith('multifamily') || f.startsWith('invest') ? '0.9' : '0.7';
      return `  <url><loc>${loc}</loc><changefreq>monthly</changefreq><priority>${priority}</priority></url>`;
    })
    .join('\n');
  fs.writeFileSync(
    path.join(DIST, 'sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`,
    'utf8'
  );

  // _redirects — preserves the existing WordPress URLs so search rankings and
  // any inbound links survive the cutover. Understood by Netlify and Cloudflare
  // Pages. On Apache/cPanel hosting use the .htaccess rules in the README.
  const redirects = [
    ['/about-us/*', '/about.html'],
    ['/services/*', '/fix-flip-buy-hold.html'],
    ['/fix-flip-buy-hold/*', '/fix-flip-buy-hold.html'],
    ['/private-money-lender/*', '/lending.html'],
    ['/investors/*', '/invest.html'],
    ['/contact-us/*', '/contact.html'],
    ['/faq/*', '/faq.html'],
    ['/terms-and-conditions/*', '/terms.html'],
    ['/privacy-policy/*', '/privacy.html'],
    ['/sell-your-house/*', '/sell.html'],
    ['/sell-your-property/*', '/sell.html'],
    ['/multifamily/*', '/multifamily.html'],
    ['/invest/*', '/invest.html'],
    ['/disclosures/*', '/disclosures.html'],
  ];
  fs.writeFileSync(
    path.join(DIST, '_redirects'),
    redirects.map(([from, to]) => `${from.padEnd(30)} ${to.padEnd(28)} 301`).join('\n') + '\n',
    'utf8'
  );

  // .htaccess — the same redirects for Apache/cPanel hosting, plus extensionless
  // URLs so /about resolves to /about.html the way it does on Netlify and Pages.
  const htaccess = [
    '# Generated by build.js — do not edit by hand.',
    'Options -MultiViews',
    'RewriteEngine On',
    '',
    '# Serve /about for /about.html',
    'RewriteCond %{REQUEST_FILENAME} !-d',
    'RewriteCond %{REQUEST_FILENAME}.html -f',
    'RewriteRule ^(.*)$ $1.html [L]',
    '',
    '# Preserve the previous WordPress URLs',
    ...redirects.map(([from, to]) => `RedirectMatch 301 ^${from.replace('/*', '/?')}$ ${to}`),
    '',
    '# Long cache for fingerprinted assets, short for HTML',
    '<IfModule mod_expires.c>',
    '  ExpiresActive On',
    '  ExpiresByType image/webp "access plus 1 year"',
    '  ExpiresByType video/mp4 "access plus 1 year"',
    '  ExpiresByType text/css "access plus 1 year"',
    '  ExpiresByType application/javascript "access plus 1 year"',
    '  ExpiresByType text/html "access plus 10 minutes"',
    '</IfModule>',
  ].join('\n') + '\n';
  fs.writeFileSync(path.join(DIST, '.htaccess'), htaccess, 'utf8');

  fs.writeFileSync(
    path.join(DIST, 'robots.txt'),
    `User-agent: *\nAllow: /\n\nSitemap: ${SITE.url}/sitemap.xml\n`,
    'utf8'
  );

  console.log(`Built ${built.length} pages:\n  ${built.join('\n  ')}\n  sitemap.xml\n  robots.txt`);
}

build();
